theme: jekyll-theme-dinky

title: Proyectos de investigación sobre COVID en Argentina
description: Se resume una lista del avance sobre los diferentes proyectos de investigación que hay en el país sobre COVID y su estado de avance.


show_downloads: false

